### ISSUE TITLE
Sign In> Incorrect toast details shown 

### ISSUE THREAD

**Issue by Anupriyabanger** [VAYUZ-Flutter-Forum/issue-tracker#56]
Change "Incorrect creds" to "Incorrect username and Password" 
![Screenshot (334)](https://github.com/VAYUZ-Flutter-Forum/issue-tracker/assets/109590553/10355286-5985-499d-bd6a-ae15d9dca028)

**Comment by technicalbirdVayuz** [comment]
changed to incorrect email or password
