### ISSUE TITLE
Sign in > Random login data not showing any error message (tried to login with social cred)

### ISSUE THREAD

**Issue by bidyut-majumdar** [VAYUZ-Flutter-Forum/issue-tracker#68]
![2023-09-25_085456](https://github.com/VAYUZ-Flutter-Forum/issue-tracker/assets/78781245/3e68d358-61de-44b9-9eb0-dcc8072efe1e)

**Comment by technicalbirdVayuz** [comment]
The message is already displayed there, that you need to enter a valid Email.

Please change the color of that error message
