### ISSUE TITLE
Homescreen > Functional > Suggestion

### ISSUE THREAD

**Issue by rgnarok** [VAYUZ-Flutter-Forum/issue-tracker#69]
![image](https://github.com/VAYUZ-Flutter-Forum/issue-tracker/assets/85341053/8b965ae6-6a64-4ed7-92de-5795f02739f3)
To change the cover image, we don't have any options.

**Comment by technicalbirdVayuz** [comment]
This is not cover image, this is banner image, changing this image is not allowed
