### ISSUE TITLE
Homescreen > Functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [VAYUZ-Flutter-Forum/issue-tracker#72]
![image](https://github.com/VAYUZ-Flutter-Forum/issue-tracker/assets/129847373/e647a470-db27-4d9d-8ebc-22b1e722ec99)
I tried to like one comment, and the forum logged out automatically.

**Comment by technicalbirdVayuz** [comment]
will add message there, you must be not logged in that' why it redirects you to sign up
