### ISSUE TITLE
Homescreen > Functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [VAYUZ-Flutter-Forum/issue-tracker#75]
![image](https://github.com/VAYUZ-Flutter-Forum/issue-tracker/assets/129847373/b6a40078-5b7a-41af-8ef0-997e59b997b1)
If I am logged in to the platform, then still Recaptcha is reflecting.

**Comment by technicalbirdVayuz** [comment]
Raja,

Captcha is not only used for login purposes, there are other pages like Create Topic or post Comments where it is being used

**Comment by rajasrivastava101** [comment]
as discussed closing this thread
